//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLChiTieu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi
    {
        public int Ma { get; set; }
        public string TenTaiKhoan { get; set; }
        public string TenChiTieu { get; set; }
        public double Gia { get; set; }
        public int Soluong { get; set; }
        public System.DateTime Thoigian { get; set; }
    }
}
