//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLChiTieu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string taiKhoan1 { get; set; }
        public string matKhau { get; set; }
    }
}
