//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLChiTieu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuVao
    {
        public int STT { get; set; }
        public string TenTK { get; set; }
        public string TenThuVao { get; set; }
        public double GiaTien { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
